---

- name: disable swap
  systemd_service:
     name: dphys-swapfile.service
     enabled: no
     state: stopped

- name: optimize logs
  ansible.posix.mount:
    src: tmpfs
    path: /var/log
    fstype: tmpfs
    opts: "defaults,noatime,nosuid,size=16m"
    state: present

- name: optimize tmp
  ansible.posix.mount:
    src: tmpfs
    path: /tmp
    fstype: tmpfs
    opts: "defaults,noatime"
    state: present

- name: "root filesystem mount"
  ansible.posix.mount:
    src: /dev/mmcblk0p2
    path: /
    fstype: ext4
    opts: "rw,noatime,commit=600"
    state: present

- name: "boot filesystem mount"
  ansible.posix.mount:
    src: /dev/mmcblk0p1
    path: /boot/firmware
    fstype: vfat
    opts: "rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro"
    state: present

- name: rpi-update
  shell: yes | rpi-update

#- name: reboot
#  reboot:
